font = { normal = { family = "Inconsolata", style = "Bold" }, size = 14 }
window = { opacity = 0.8, padding = { x = 0, y = 0}, dynamic_padding = true }
mouse = { bindings = [{ mouse = "Middle", action = "PasteSelection" }] }
# maybe we can have font size stuff
